import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Pokedex from "@/components/Pokedex"
import GlobalContextProvider from '@/context/GlobalContext'
import GlobalContext from '@/context/GlobalContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}



export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div
			style={{
				display        :"flex",
				width          :"100%",
				height         :"100%",
				justifyContent :"center",
				alignItems     :"center"
			}}>
			<GlobalContextProvider>
				{children}
				<Pokedex/>
			</GlobalContextProvider>
		</div>
	)
}
