version: '3'

services:
  test_technique:
    image          : node:lts
    ports          : ["${NEXT_PORT}"] 
    restart        : always
    working_dir    : /home/node/app/
    command        : sh -c "${NEXT_COMMAND}"
    volumes        : [./next:/home/node/app]
    environment     :
      NODE_ENV    : "${NODE_ENV}"
